#!/bin/bash

echo "* Generating coins..."
sleep 2

bitcoin-cli -conf=/etc/conf/node-1/bitcoin.conf generate 101 > /dev/null
bitcoin-cli -conf=/etc/conf/node-2/bitcoin.conf generate 101 > /dev/null
echo "* Done!"

s6-svc -d /var/run/s6/services/pregenerate
