#!/bin/sh

echo "* Bitcoind node 1..."
exec /usr/bin/bitcoind \
    --printtoconsole \
    -datadir=/data/node-1 \
    -conf=/etc/conf/node-1/bitcoin.conf \
    -server \
    -walletnotify='/bin/push-transaction.sh /etc/conf/node-1/bitcoin.conf %s /var/run/bitcoind/events-in' \
    -blocknotify='/bin/push-block.sh %s /var/run/bitcoind/events-in'
