#!/bin/sh

echo "* Bitcoind node 1..."
exec /usr/bin/bitcoind \
    --printtoconsole \
    -datadir=/data/node-1 \
    -conf=/etc/conf/node-1/bitcoin.conf \
    -server \
    -walletnotify='/usr/bin/bitcoin-cli -conf=/data/bitcoin.conf gettransaction %s | tr "\n" " " | sed "s/$/\n/"  > /var/run/bitcoind/events-in' \
    -blocknotify='echo %s > /var/run/bitcoind/events-in'
